server:
  port: ${APP_PORT:8081}
spring:
  application:
    name: tt-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tt_tasks}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  rabbitmq:
    addresses:
      - localhost:5672
    username: ${RMQ_USERNAME:guest}
    password: ${RMQ_PASSWORD}
    virtual-host: ttLogHost
springdoc:
  swagger-ui:
    path: swagger-ui
  open-api:
    info:
      title: Task Tracker Service
      description: Микросервис для работы с задачами системы Task Tracker
      version: 1.0.0
user-service:
  baseUrl: ${USER_SERVICE_URL:http://localhost:8080/api/v1}
app:
  rabbitmq:
    queue: ttLogHost-queue
    exchange: ttLogHost-exchange
